Repository googleinterns/step224-2020, pull requests merged in 2020-09, with the labels that each got.

#34 File generating function
  hermes/file_gen.go
Labels: need to do, shared

#37 Testing file_gen.go
  hermes/file_gen_test.go
Labels: shared

#50 Altered protos as per code review.
  config/proto/interface.pb.go
  config/proto/interface.proto
  config/proto/probe.pb.go
  config/proto/probe.proto
  config/proto/service.pb.go
  config/proto/service.proto
  config/proto/targets.pb.go
  config/proto/targets.proto
Labels: shared

#46 Added probe config proto and compiled proto for GCS: Delete File operation.
  gcs/deleteFile/proto/deleteFile.pb.go
  gcs/deleteFile/proto/deleteFile.proto
Labels: GCS

#36 Integrated Cloudprober as an extension and setup Client gRPC server.
  cmd/client.go
  cmd/client_test.go
  config/proto/probe.proto
  config/proto/service.proto
  config/proto/targets.proto
  hermes/hermes.go
  hermes/proto/state_journal.pb.go
  hermes/proto/state_journal.proto
  main.go
Labels: shared

#52 Restructured packages and removes DeleteFileProbe proto.
  client/client.go
  client/client_test.go
  config/proto/probe.pb.go
  config/proto/probe.proto
  config/proto/service.pb.go
  config/proto/service.proto
  config/proto/targets.pb.go
  config/proto/targets.proto
  gcs/deleteFile/proto/deleteFile.pb.go
  gcs/deleteFile/proto/deleteFile.proto
  hermes/file_gen.go
  hermes/file_gen_test.go
  hermes/hermes.go
  hermes/proto/state_journal.proto
  main.go
  test.sh
  testMain/main.go
Labels: shared

#59 Added struct values and Init() to monitor.go
  hermes/hermes.go
  hermes/probe/metrics/metrics.go
  hermes/probe/monitor.go
  hermes/probe/probe.go
  hermes/probe/probe_test.go
Labels: GCS

#57 create_file function and unit tests for it
  hermes/probe/create/create.go
  hermes/probe/create/create_test.go
Labels: GCS

#71 created the ReadFile function and unit tests
  hermes/probe/read/read.go
  hermes/probe/read/read_test.go
Labels: GCS

#82 Fixed bug in metrics reporting, deleted deprecated files.
  hermes/file_gen.go
  hermes/file_gen_test.go
  hermes/probe/create/create.go
  hermes/probe/create/create_test.go
  hermes/probe/delete/delete.go
  hermes/probe/delete/delete_test.go
  hermes/probe/metrics/metrics.go
  hermes/probe/probe.go
  hermes/probe/read/read.go
  hermes/probe/read/read_test.go
  hermes/probe/target/target.go
Labels: GCS, bug
